# Generated by Django 5.2.4 on 2025-08-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_mesa_mueble_silla_sofa_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silla',
            old_name='fecha_fabricacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='sofa',
            old_name='fecha_produccion',
            new_name='fecha',
        ),
    ]
